# Generated by Django 5.2.7 on 2025-10-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='option_one',
            field=models.CharField(default='Option 1', max_length=30),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_one_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_three',
            field=models.CharField(default='Option 3', max_length=30),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_three_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_two',
            field=models.CharField(default='Option 2', max_length=30),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_two_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.TextField(default='New Question'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
