# Generated by Django 5.2.7 on 2025-11-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='num_options',
            field=models.IntegerField(choices=[(2, '2 options'), (3, '3 options'), (4, '4 options')], default=3),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_four',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_four_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_one',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_three',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_two',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(max_length=200),
        ),
    ]
