# Generated by Django 5.2.7 on 2025-11-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_backfill_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Controls whether this poll appears on the home page list.'),
        ),
    ]
