# Generated by Django 5.2.7 on 2025-11-12 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_poll_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Audience categories',
            },
        ),
        migrations.CreateModel(
            name='AudienceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.audiencecategory')),
            ],
            options={
                'ordering': ['category__name', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='poll',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Restrict visibility to selected audience options (leave empty for everyone).', related_name='polls', to='main.audienceoption'),
        ),
    ]
