# Generated by Django 5.2.7 on 2025-11-15 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_useraudienceoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='BerlinPostalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('bezirk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postal_codes', to='main.audienceoption')),
            ],
            options={
                'verbose_name': 'Berlin postal code',
                'verbose_name_plural': 'Berlin postal codes',
            },
        ),
    ]
