# Generated by Django 5.2.6 on 2025-11-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_seed_berlin_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='main_emailv_email_47fc12_idx'), models.Index(fields=['code'], name='main_emailv_code_c73b87_idx')],
            },
        ),
    ]
