# Generated by Django 5.2.7 on 2025-11-26 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_poll_num_options_poll_option_four_and_more'),
        ('main', '0013_seed_berlin_city'),
    ]

    operations = [
    ]
